name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Set name'
        required: true
        default: 'github-actions'
        type: string
      environment:
        description: 'Set env'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world!
      - name: step2
        run: |
          echo hello world!
          echo github action!
      - name: step3
        run: |
          echo ${{ github.event.inputs.name }}
          echo ${{ github.event.inputs.environment }}
