name: pull-request-workflow
on:
  # https://docs.github.com/ko/actions/using-workflows/events-that-trigger-workflows#pull_request
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world!
    - name: step2
      run: |
        echo hello world!
        echo github action!
