name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'Prefix for the repository name'
        required: true
        default: 'service'
        type: choice
        options:
          - 'service'
          - 'example'
      name:
        description: 'Name of the repository'
        required: true
        default: 'my-repo'
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
      - name: create repo
        id: create-repo
        run: |
          gh repo create jaime-github-action/${{ inputs.prefix }}-${{ inputs.name }} --public --add-readme
      - name: slack
        if: always()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#28a745",
                  "pretext": "Create Repository Result",
                  "fields": [
                      {
                      "title": "Create Repository Result ${{ steps.create-repo.outcome }}",
                      "short": true,
                      "value": "Repository ${{ inputs.prefix }}-${{ inputs.name }}"
                      }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
