name: issue-notify
on:
  issues:
    types:
      - opened

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      keyword: ${{ steps.get-keyword.outputs.level }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get keyword
        id: get-keyword
        run: |
          echo level=undefined >> $GITHUB_OUTPUT
          
          keywords=$(cat keywords.txt)
          for keyword in $keywords; do
            if [[ "${{ github.event.issue.title }}" =~ "$keyword" ]]; then
              echo level=$keyword >> $GITHUB_OUTPUT
            fi
          done
      - name: Get output
        run: echo ${{ steps.get-keyword.outputs.level }}

  slack:
    needs:
      - get-keyword
    if: needs.get-keyword.outputs.level != 'undefined'
    runs-on: ubuntu-latest
    environment: ${{ needs.get-keyword.outputs.level }}
    steps:
      - name: Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": "New issue opened",
                  "title": "${{ github.event.issue.title }}",
                  "title_link": "${{ github.event.issue.html_url }}",
                  "text": "${{ github.event.issue.body }}",
                  "fields": [
                    {
                      "title": "Level: ${{ needs.get-keyword.outputs.level }}",
                      "short": true,
                      "value": "Issue url: ${{ github.event.issue.html_url }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

